// {
//     req: <ref *1> IncomingMessage {
//       _readableState: ReadableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//         pipes: [],
//         flowing: true,
//         ended: true,
//         endEmitted: true,
//         reading: false,
//         constructed: true,
//         sync: false,
//         needReadable: false,
//         emittedReadable: false,
//         readableListening: false,
//         resumeScheduled: false,
//         errorEmitted: false,
//         emitClose: true,
//         autoDestroy: true,
//         destroyed: false,
//         errored: null,
//         closed: false,
//         closeEmitted: false,
//         defaultEncoding: 'utf8',
//         awaitDrainWriters: null,
//         multiAwaitDrain: false,
//         readingMore: false,
//         dataEmitted: true,
//         decoder: null,
//         encoding: null,
//         [Symbol(kPaused)]: false
//       },
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       socket: Socket {
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: null,
//         _closeAfterHandlingError: false,
//         _readableState: [ReadableState],
//         _events: [Object: null prototype],
//         _eventsCount: 8,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         allowHalfOpen: true,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: [Server],
//         _server: [Server],
//         parser: [HTTPParser],
//         on: [Function: socketListenerWrap],
//         addListener: [Function: socketListenerWrap],
//         prependListener: [Function: socketListenerWrap],
//         setEncoding: [Function: socketSetEncoding],
//         _paused: false,
//         _httpMessage: [ServerResponse],
//         _peername: [Object],
//         [Symbol(async_id_symbol)]: 56,
//         [Symbol(kHandle)]: [TCP],
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: false,
//         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       httpVersionMajor: 1,
//       httpVersionMinor: 1,
//       httpVersion: '1.1',
//       complete: true,
//       rawHeaders: [
//         'content-length',
//         '51',
//         'accept-encoding',
//         'gzip, deflate, br',
//         'Accept',
//         '*/*',
//         'User-Agent',
//         'Thunder Client (https://www.thunderclient.com)',
//         'Content-Type',
//         'application/json',
//         'Host',
//         'localhost:3000',
//         'Connection',
//         'close'
//       ],
//       rawTrailers: [],
//       aborted: false,
//       upgrade: false,
//       url: '/',
//       method: 'POST',
//       statusCode: null,
//       statusMessage: null,
//       client: Socket {
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: null,
//         _closeAfterHandlingError: false,
//         _readableState: [ReadableState],
//         _events: [Object: null prototype],
//         _eventsCount: 8,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         allowHalfOpen: true,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: [Server],
//         _server: [Server],
//         parser: [HTTPParser],
//         on: [Function: socketListenerWrap],
//         addListener: [Function: socketListenerWrap],
//         prependListener: [Function: socketListenerWrap],
//         setEncoding: [Function: socketSetEncoding],
//         _paused: false,
//         _httpMessage: [ServerResponse],
//         _peername: [Object],
//         [Symbol(async_id_symbol)]: 56,
//         [Symbol(kHandle)]: [TCP],
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: false,
//         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       _consuming: true,
//       _dumped: false,
//       next: [Function: next],
//       baseUrl: '/v1/login',
//       originalUrl: '/v1/login',
//       _parsedUrl: Url {
//         protocol: null,
//         slashes: null,
//         auth: null,
//         host: null,
//         port: null,
//         hostname: null,
//         hash: null,
//         search: null,
//         query: null,
//         pathname: '/',
//         path: '/',
//         href: '/',
//         _raw: '/'
//       },
//       params: {},
//       query: {},
//       res: ServerResponse {
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: false,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: false,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: true,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: null,
//         _hasBody: true,
//         _trailer: '',
//         finished: false,
//         _headerSent: false,
//         _closed: false,
//         socket: [Socket],
//         _header: null,
//         _keepAliveTimeout: 5000,
//         _onPendingData: [Function: bound updateOutgoingData],
//         req: [Circular *1],
//         _sent100: false,
//         _expect_continue: false,
//         _maxRequestsPerSocket: 0,
//         locals: [Object: null prototype] {},
//         _startAt: undefined,
//         _startTime: undefined,
//         writeHead: [Function: writeHead],
//         __onFinished: [Function],
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kEndCalled)]: false,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype],
//         [Symbol(kUniqueHeaders)]: null
//       },
//       body: { username: 'admin', password: 'adminPassword' },
//       _body: true,
//       length: undefined,
//       _startAt: [ 225320, 511378100 ],
//       _startTime: 2024-05-18T03:44:34.535Z,
//       _remoteAddress: '::ffff:127.0.0.1',
//       route: Route { path: '/', stack: [Array], methods: [Object] },
//       [Symbol(kCapture)]: false,
//       [Symbol(kHeaders)]: {
//         'content-length': '51',
//         'accept-encoding': 'gzip, deflate, br',
//         accept: '*/*',
//         'user-agent': 'Thunder Client (https://www.thunderclient.com)',
//         'content-type': 'application/json',
//         host: 'localhost:3000',
//         connection: 'close'
//       },
//       [Symbol(kHeadersCount)]: 14,
//       [Symbol(kTrailers)]: null,
//       [Symbol(kTrailersCount)]: 0
//     }
//   }

//   { username: 'admin', password: 'adminPassword' }

//   POST /v1/login 200 84.988 ms - 171

//   {
//     req: <ref *1> IncomingMessage {
//       _readableState: ReadableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//         pipes: [],
//         flowing: null,
//         ended: false,
//         endEmitted: false,
//         reading: false,
//         constructed: true,
//         sync: true,
//         needReadable: false,
//         emittedReadable: false,
//         readableListening: false,
//         resumeScheduled: false,
//         errorEmitted: false,
//         emitClose: true,
//         autoDestroy: true,
//         destroyed: false,
//         errored: null,
//         closed: false,
//         closeEmitted: false,
//         defaultEncoding: 'utf8',
//         awaitDrainWriters: null,
//         multiAwaitDrain: false,
//         readingMore: true,
//         dataEmitted: false,
//         decoder: null,
//         encoding: null,
//         [Symbol(kPaused)]: null
//       },
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       socket: Socket {
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: null,
//         _closeAfterHandlingError: false,
//         _readableState: [ReadableState],
//         _events: [Object: null prototype],
//         _eventsCount: 8,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         allowHalfOpen: true,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: [Server],
//         _server: [Server],
//         parser: [HTTPParser],
//         on: [Function: socketListenerWrap],
//         addListener: [Function: socketListenerWrap],
//         prependListener: [Function: socketListenerWrap],
//         setEncoding: [Function: socketSetEncoding],
//         _paused: false,
//         _httpMessage: [ServerResponse],
//         _peername: [Object],
//         [Symbol(async_id_symbol)]: 72,
//         [Symbol(kHandle)]: [TCP],
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: false,
//         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       httpVersionMajor: 1,
//       httpVersionMinor: 1,
//       httpVersion: '1.1',
//       complete: false,
//       rawHeaders: [
//         'content-type',
//         'multipart/form-data; boundary=--------------------------853347300410762204478396',
//         'content-length',
//         '288',
//         'accept-encoding',
//         'gzip, deflate, br',
//         'Accept',
//         '*/*',
//         'User-Agent',
//         'Thunder Client (https://www.thunderclient.com)',
//         'Host',
//         'localhost:3000',
//         'Connection',
//         'close'
//       ],
//       rawTrailers: [],
//       aborted: false,
//       upgrade: false,
//       url: '/',
//       method: 'POST',
//       statusCode: null,
//       statusMessage: null,
//       client: Socket {
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: null,
//         _closeAfterHandlingError: false,
//         _readableState: [ReadableState],
//         _events: [Object: null prototype],
//         _eventsCount: 8,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         allowHalfOpen: true,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: [Server],
//         _server: [Server],
//         parser: [HTTPParser],
//         on: [Function: socketListenerWrap],
//         addListener: [Function: socketListenerWrap],
//         prependListener: [Function: socketListenerWrap],
//         setEncoding: [Function: socketSetEncoding],
//         _paused: false,
//         _httpMessage: [ServerResponse],
//         _peername: [Object],
//         [Symbol(async_id_symbol)]: 72,
//         [Symbol(kHandle)]: [TCP],
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: false,
//         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       _consuming: false,
//       _dumped: false,
//       next: [Function: next],
//       baseUrl: '/v1/login',
//       originalUrl: '/v1/login',
//       _parsedUrl: Url {
//         protocol: null,
//         slashes: null,
//         auth: null,
//         host: null,
//         port: null,
//         hostname: null,
//         hash: null,
//         search: null,
//         query: null,
//         pathname: '/',
//         path: '/',
//         href: '/',
//         _raw: '/'
//       },
//       params: {},
//       query: {},
//       res: ServerResponse {
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: false,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: false,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: true,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: null,
//         _hasBody: true,
//         _trailer: '',
//         finished: false,
//         _headerSent: false,
//         _closed: false,
//         socket: [Socket],
//         _header: null,
//         _keepAliveTimeout: 5000,
//         _onPendingData: [Function: bound updateOutgoingData],
//         req: [Circular *1],
//         _sent100: false,
//         _expect_continue: false,
//         _maxRequestsPerSocket: 0,
//         locals: [Object: null prototype] {},
//         _startAt: undefined,
//         _startTime: undefined,
//         writeHead: [Function: writeHead],
//         __onFinished: [Function],
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kEndCalled)]: false,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype],
//         [Symbol(kUniqueHeaders)]: null
//       },
//       body: {},
//       _startAt: [ 225326, 858407000 ],
//       _startTime: 2024-05-18T03:44:40.882Z,
//       _remoteAddress: '::ffff:127.0.0.1',
//       route: Route { path: '/', stack: [Array], methods: [Object] },
//       [Symbol(kCapture)]: false,
//       [Symbol(kHeaders)]: {
//         'content-type': 'multipart/form-data; boundary=--------------------------853347300410762204478396',
//         'content-length': '288',
//         'accept-encoding': 'gzip, deflate, br',
//         accept: '*/*',
//         'user-agent': 'Thunder Client (https://www.thunderclient.com)',
//         host: 'localhost:3000',
//         connection: 'close'
//       },
//       [Symbol(kHeadersCount)]: 14,
//       [Symbol(kTrailers)]: null,
//       [Symbol(kTrailersCount)]: 0
//     }
//   }
